import type { DashboardData } from "./types";

const now = new Date().toISOString();

export const demoData: DashboardData = {
  health: "healthy",
  health_message: "本地学习与权威知识索引运行正常",
  pending_count: 3,
  counts: { preference: 12, fact: 31, experience: 18, procedure: 7 },
  growth: [8, 11, 13, 16, 21, 25, 30],
  candidates: [
    {
      id: "candidate-evidence",
      type: "preference",
      title: "完成声明前优先提供证据",
      summary: "用户持续要求将实现、自测、CI 与真实验收分开陈述。",
      scope: "global",
      status: "candidate",
      explicitness: "explicit",
      confidence: 0.96,
      source_refs: ["coaching-trace:trace-adapters"],
      evidence_refs: ["acceptance:M0-product-review", "acceptance:M0-technical-review"],
      updated_at: now,
    },
    {
      id: "candidate-readback",
      type: "procedure",
      title: "安装后必须读回宿主配置",
      summary: "集成写入完成后运行 fresh-process discovery；失败时恢复原始配置。",
      scope: "project:agent-coach",
      status: "candidate",
      explicitness: "inferred",
      confidence: 0.82,
      source_refs: ["experience:managed-agent-integrations"],
      evidence_refs: ["test:sentinel-preservation", "test:rollback"],
      updated_at: now,
    },
    {
      id: "candidate-loop",
      type: "fact",
      title: "禁止重新捕获已注入 Context",
      summary: "origin=agent-coach 的 GuidancePacket 必须在 Capture 入口被排除。",
      scope: "project:agent-coach",
      status: "candidate",
      explicitness: "explicit",
      confidence: 1,
      source_refs: ["contract:ARCHITECTURE#retrieval"],
      evidence_refs: ["fixture:injection-loop"],
      updated_at: now,
    },
  ],
  traces: [
    {
      id: "trace-adapters",
      title: "交付 Agent-neutral 记忆适配器",
      host: "Codex",
      time: "今天 10:42",
      status: "executing",
      matches: 4,
      before: ["按宿主分别保存记忆", "优先快速落地", "只记录关键里程碑"],
      after: ["使用统一 Agent-neutral Core", "完成声明前优先提供证据", "每个适配器必须读回与回滚"],
      adopted: ["完成声明前优先提供证据", "集成写入后执行 fresh-process readback"],
      omitted: ["旧 DSH rc.6 版本锁：当前已是 rc.7"],
      outcome: "实现中；Ticket epoch 已建立",
    },
    {
      id: "trace-privacy",
      title: "关闭 localhost 未认证写接口",
      host: "Kimi Code",
      time: "昨天 22:18",
      status: "completed",
      matches: 3,
      before: ["仅限制到 127.0.0.1"],
      after: ["Bearer + SameSite session + CSRF", "发现文件不含 secret"],
      adopted: ["loopback 不是认证"],
      omitted: [],
      outcome: "安全合同已通过独立复审",
    },
  ],
  integrations: [
    { id: "codex", name: "Codex", version: "0.147.0", status: "verified", detail: "Plugin、MCP 与 Hook wire 已发现", coverage: "Bash · apply_patch · MCP · local tools" },
    { id: "kimi", name: "Kimi Code", version: "0.38.0", status: "verified", detail: "Plugin ZIP 与 Hook fixture 已验证", coverage: "UserPromptSubmit · PreToolUse · Stop" },
    { id: "dsh", name: "DeepSeek Harness", version: "0.1.0-rc.7", status: "unverified", detail: "Bundle 已生成，等待 packed-install", coverage: "agent/pre-step · tools/pre-execute" },
  ],
  memories: [
    { id: "memory-evidence", type: "preference", title: "证据优先", content: "不要把讨论、自测或超时当作已完成。", scope: "global", status: "approved", uses: 9, feedback: 4, source: "用户明确偏好", updated_at: now },
    { id: "memory-thin-adapter", type: "fact", title: "宿主适配器保持薄", content: "业务核心归 Agent Coach，宿主只做协议与生命周期翻译。", scope: "project:agent-coach", status: "approved", uses: 6, feedback: 2, source: "架构合同", updated_at: now },
    { id: "memory-gateway", type: "experience", title: "localhost 也需要认证", content: "恶意网页可访问本地端口；必须有 Bearer、Origin 与 CSRF。", scope: "global", status: "approved", uses: 3, feedback: 2, source: "M0 独立审查", updated_at: now },
    { id: "memory-readback", type: "procedure", title: "配置写入后读回", content: "preview → apply → readback → fresh process → rollback on failure。", scope: "global", status: "approved", uses: 7, feedback: 3, source: "已验证集成流程", updated_at: now },
  ],
  settings: { learning_paused: false, recall_enabled: true, gate_mode: "advisory", journal_ttl_days: 30, diagnostic_capture_ttl_days: 7, provider_consent: false },
  provider: { name: "Built-in", status: "healthy", detail: "File knowledge + SQLite FTS5" },
  demo: true,
};
